# -*- coding: utf-8 -*-
"""Basketball player statistic data sci

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ICjSO7M2GpttDsIuLmDbumKF1rNzRzNt
"""

def get_preformance_level(points):
  if points >= 45:
    return "star player"
  elif points >= 30:
    return "Great player"
  elif points >= 15:
    return "Good player"
  elif points >= 5:
    return "Bench warmer"
  elif points >= 1:
    return "Improving player"
  else:
    return "Did not score"

def calculate_avg(players):
  total = 0
  for player in players:
    total += player["points"]
  return total/len(players)

def highest_scorer(players):
  top = players[0]
  for player in players:
    if player["points"]>top["points"]:
      top  = player
  return top

def lowest_scorer(players):
  low = players[0]
  for player in players:
    if player["points"]<low["points"]:
      low = player
  return low

players = []

num_players = int(input("Enter number of basketball players"))

for i in range(num_players):
  print(f"\nPlayer {i+1}")
  name = input("Enter player's name: ")
  points = int(input("Points scored:"))

  players.append({
      "name": name,
      "points": points
  })

print("\nPlayer Report\n")

for player in players:
  level = get_preformance_level(player["points"])
  print(
      f"Name: {player['name']} |"
      f"Points: {player['points']} |"
      f"Level: {level}"
  )

print("\nSummary")
avg= calculate_avg(players)
top = highest_scorer(players)
low = lowest_scorer(players)
print(f"Average Points: {avg:.2f}")
print(f"Top Scorer:  {top['name']}({top['points']}points)")
print(f"Lowest Scorer: {low['name']}({low['points']}points)")